version: '3.3'
services:
    config-server:
        image: config-server:latest
        container_name: config-server-container
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network


    service-registry-server:
        image: service-registry:latest
        container_name: service-registry-container
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network

    database:
        image: mysql:8
        container_name: mysql-container
        ports:
            - 3306:3306
        networks:
            - spring-cloud-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=inbox_schema


    auth-server:
        image: auth-service:latest
        container_name: auth-server-container
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        environment:
            - RDS_HOSTNAME=database
            - RDS_PORT=3306
            - RDS_DB_NAME=inbox_schema
            - SERVICEREGISTRY_HOSTNAME=service-registry-container
            - SERVICEREGISTRY_PORT=8761
        depends_on:
            - database
            - service-registry-server


    admin-server:
        image: admin-service:latest
        container_name: admin-service-container
        ports:
            - 8085:8085
        networks:
            - spring-cloud-network
        environment:
            - RDS_HOSTNAME=database
            - RDS_PORT=3306
            - RDS_DB_NAME=inbox_schema
            - SERVICEREGISTRY_HOSTNAME=service-registry-container
            - SERVICEREGISTRY_PORT=8761
            - CONFIG_HOSTNAME=config-server-container
            - CONFIG_PORT=8888
            - AUTH_HOSTNAME=auth-server-container
            - AUTH_PORT=8080
        depends_on:
            - database
            - service-registry-server
            - config-server
            - auth-server



    patient-server:
        image: patient-service:latest
        container_name: patient-service-container
        ports:
            - 8082:8082
        networks:
            - spring-cloud-network
        environment:
            - RDS_HOSTNAME=database
            - RDS_PORT=3306
            - RDS_DB_NAME=inbox_schema
            - SERVICEREGISTRY_HOSTNAME=service-registry-container
            - SERVICEREGISTRY_PORT=8761
            - CONFIG_HOSTNAME=config-server-container
            - CONFIG_PORT=8888
        depends_on:
            - database
            - service-registry-server
            - config-server

    inbox-server:
        image: inbox-server:latest
        container_name: inbox-container
        ports:
            - 8081:8081
        networks:
            - spring-cloud-network
        environment:
            - RDS_HOSTNAME=database
            - RDS_PORT=3306
            - RDS_DB_NAME=inbox_schema
            - SERVICEREGISTRY_HOSTNAME=service-registry-container
            - SERVICEREGISTRY_PORT=8761
            - CONFIG_HOSTNAME=config-server-container
            - CONFIG_PORT=8888
        depends_on:
            - database
            - service-registry-server
            - config-server

networks:
    spring-cloud-network:
        driver: bridge
